# Generated by Django 5.0.2 on 2024-03-06 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_to_do', models.CharField(blank=True, max_length=255, null=True, verbose_name='Место')),
                ('time_to_do', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время')),
                ('action', models.CharField(blank=True, max_length=255, null=True, verbose_name='Действие')),
                ('is_good', models.BooleanField(blank=True, default=None, null=True, verbose_name='Признак приятной привычки')),
                ('periodicity', models.IntegerField(default=1, verbose_name='Периодичность')),
                ('reward', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вознаграждение')),
                ('time_required', models.TimeField(blank=True, null=True, verbose_name='Время на выполнение')),
                ('is_public', models.BooleanField(default=False, verbose_name='Признак публичности')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_habit', to='habits.habit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
