# Generated by Django 5.0.2 on 2024-03-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habit_related_habit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time_required',
            field=models.DurationField(blank=True, null=True, verbose_name='Время на выполнение'),
        ),
    ]
