# Generated by Django 5.0.2 on 2024-03-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_habit_time_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time_to_do',
            field=models.TimeField(auto_now_add=True, null=True, verbose_name='Время'),
        ),
    ]
