# Generated by Django 5.0.2 on 2024-03-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_alter_habit_time_to_do'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='time_to_do',
            field=models.TimeField(blank=True, null=True, verbose_name='Время'),
        ),
    ]
